[package]
name = "compress"
version = "0.1.0"
edition = "2021"
description="Program to compress bw videos and output binary files"

[dependencies]
thiserror={version="2.0.11"}
clap={version="4.5.26", features=["derive"]}
image="0.25.5"
